/*
 * generated by Xtext 2.11.0
 */
package hu.bzolt.webdsl.tests

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(WebDslInjectorProvider)
class WebDslParsingTest
{
//	@Inject
//	ParseHelper<DomainModel> parseHelper
//	
//	@Test
//	def void loadModel() {
//		val result = parseHelper.parse('''
//			Hello Xtext!
//		''')
//		Assert.assertNotNull(result)
//		Assert.assertTrue(result.eResource.errors.isEmpty)
//	}
}
