/*
 * generated by Xtext 2.11.0
 */
package hu.bzolt.webdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WebDslStandaloneSetup extends WebDslStandaloneSetupGenerated {

	def static void doSetup() {
		new WebDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
