/*
 * generated by Xtext 2.11.0
 */
package hu.bzolt.webdsl.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class WebDslScopeProvider extends AbstractWebDslScopeProvider {

}
